services:
  postgres:
    image: postgres:15.3
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - internal-net
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    command: >
      bash -c "
        docker-entrypoint.sh postgres &
        sleep 5 &&
        psql -U postgres -c 'CREATE DATABASE keycloak;' &&
        psql -U postgres -c 'CREATE DATABASE appdb;' &&
        wait
      "

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    command: start-dev --import-realm
    environment:
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://postgres:5432/keycloak
      - KC_DB_USERNAME=postgres
      - KC_DB_PASSWORD=password
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
    volumes:
      - ./keycloak-realm-config:/opt/keycloak/data/import
    ports:
      - "8181:8080"
    depends_on:
      - postgres
    networks:
      - internal-net
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - internal-net

#  spring-boot-app:
#    build: .
#    container_name: spring-boot-app
#    depends_on:
#      - keycloak
#    ports:
#      - "8080:8080"
#    environment:
#      # --- Database Config ---
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/appdb
#      - SPRING_DATASOURCE_DRIVER-CLASS-NAME=org.postgresql.Driver
#      - SPRING_DATASOURCE_USERNAME=postgres
#      - SPRING_DATASOURCE_PASSWORD=password
#      - SPRING_JPA_DATABASE-PLATFORM=org.hibernate.dialect.PostgreSQLDialect
#      # Removed hibernate.ddl-auto to rely on JPA default (no automatic schema changes)
#      # --- Keycloak Integration ---
#      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=http://keycloak:8080/realms/my-realm
#      - APP_KEYCLOAK_REALM=my-realm
#      - APP_KEYCLOAK_CLIENT_ID=my-spring-boot-client
#      - APP_KEYCLOAK_CLIENT_SECRET=
#    networks:
#      - internal-net

volumes:
  postgres_data:
  pgadmin-data:

networks:
  internal-net:
    driver: bridge
