# k8s/postgresql/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-initdb
data:
  init-user-db.sh: |
    #!/bin/bash
    set -e
    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
      CREATE USER keycloak_user WITH PASSWORD 'keycloak_pass';
      CREATE DATABASE keycloakdb OWNER keycloak_user;

    EOSQL