# k8s/03-secrets/app-secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  POSTGRES_USER: cGxheWdyb3VuZHVzZXI= # playgrounduser (base64 encoded)
  POSTGRES_PASSWORD: cGxheWdyb3VuZHBhc3N3b3Jk # playgroundpassword (base64 encoded)
  REDIS_PASSWORD: cGFzc3dvcmQ= # password (base64 encoded "password")
  KEYCLOAK_CLIENT_SECRET: QkZpTFZOMzA5Rm5YRFRUbUpSYVJCZ0hNZUw1aG10c2s= # BFiLVN309FnXDTTmJRaRBgHMeL5hmtsk
  KC_BOOTSTRAP_ADMIN_USERNAME: YWRtaW4= # admin (base64 encoded "password")
  KC_BOOTSTRAP_ADMIN_PASSWORD: YWRtaW4= # admin (base64 encoded "password")